spring.application.name=household-account-book-app

# ------------------------------
# 共通設定（local / prod 共通）
# ------------------------------

# MyBatis設定（どの環境でも同じ）
mybatis.mapper-locations=classpath*:mappers/*.xml
mybatis.type-aliases-package=jp.educure.household_account_book.entity
mybatis.configuration.map-underscore-to-camel-case=true

# ログ（必要なら共通でOK）
logging.level.com.example.webapp.repository=DEBUG

# 起動時に使うプロファイル（ローカルでは local を使う）
spring.profiles.active=local