# ------------------------------
# 本番環境(prod)の設定
# ------------------------------

# 本番DBは環境変数から受け取る（直書きしない）
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${JDBC_DATABASE_URL}
spring.datasource.username=${JDBC_DATABASE_USERNAME}
spring.datasource.password=${JDBC_DATABASE_PASSWORD}

# 本番環境では schema.sql を絶対に自動実行しない
spring.sql.init.mode=never
spring.sql.init.encoding=UTF-8

# 本番ではキャッシュONが基本（パフォーマンスと安定）
spring.thymeleaf.cache=true
