# ------------------------------
# ローカル環境(local)の設定
# ------------------------------

# DataSourceの設定（ローカルPostgreSQL）
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/kakeibo_db
spring.datasource.username=postgres
spring.datasource.password=CYV94XpcfV

# schema.sql をローカル起動時に流す
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8

# 開発効率のための設定（本番環境には絶対いらない）
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=file:src/main/resources/templates/

spring.web.resources.static-locations=file:src/main/resources/static/
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false

spring.devtools.livereload.enabled=true
