spring.application.name=household-account-book-app

# DataSourceの設定
# PostgreSQLドライバーの設定
spring.datasource.driver-class-name=org.postgresql.Driver
# データベースへのURLを設定
spring.datasource.url=jdbc:postgresql://localhost:5432/kakeibo_db
# データベース接続のためのユーザー名を設定
spring.datasource.username=postgres
# データベース接続のためのパスワードを設定
spring.datasource.password=CYV94XpcfV
# SQLスクリプトの初期化モードを設定
spring.sql.init.mode=always
# ログ設定
logging.level.com.example.webapp.repository=DEBUG
# schema.sql / data.sql など、起動時に実行されるSQLの文字コードを指定
spring.sql.init.encoding=UTF-8

# MyBatis設定
mybatis.mapper-locations=classpath*:mappers/*.xml
mybatis.type-aliases-package=jp.educure.household_account_book.entity
mybatis.configuration.map-underscore-to-camel-case=true

# Thymeleafテンプレートをキャッシュしない（HTMLを保存→即反映）
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=file:src/main/resources/templates/

# 静的リソースもソースから直読み
spring.web.resources.static-locations=file:src/main/resources/static/
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false

# LiveReload（ブラウザの自動リロード）を有効化
spring.devtools.livereload.enabled=true