-- 既に存在する場合は削除
DROP TABLE IF EXISTS goals CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS users CASCADE;


CREATE TABLE users (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- ID（自動採番）
  user_name   VARCHAR(50)  NOT NULL UNIQUE,                         -- ユーザーネーム（UK）
  email       VARCHAR(255) NOT NULL UNIQUE,                         -- メールアドレス（UK）
  password    VARCHAR(100) NOT NULL,                                -- パスワード（ハッシュ想定）
  is_admin    BOOLEAN      NOT NULL DEFAULT FALSE,                  -- 管理者フラグ
  deleted     BOOLEAN      NOT NULL DEFAULT FALSE,                  -- 退会フラグ
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),                  -- 登録日時
  updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()                   -- 更新日時
);

CREATE TABLE categories (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name        VARCHAR(50) NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uk_categories_user_name UNIQUE (user_id, name)
);

CREATE TABLE transactions (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  category_id INTEGER     REFERENCES categories(id) ON DELETE SET NULL,
  amount      INTEGER  NOT NULL,
  txn_date    DATE     NOT NULL,                                    -- 取引日
  direction   VARCHAR(8) NOT NULL,                                   -- IN/OUT
  memo        VARCHAR(255),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at  TIMESTAMPTZ,                                           -- 論理削除用（NULL=有効）
  CONSTRAINT chk_transactions_direction
    CHECK (direction IN ('IN','OUT')),
  CONSTRAINT chk_transactions_amount_nonneg
    CHECK (amount >= 0)
);

CREATE TABLE goals (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       INTEGER   NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  year_month    CHAR(7)   NOT NULL,           -- 'YYYY-MM'
  target_amount INTEGER   NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uk_goals_user_month UNIQUE (user_id, year_month),
  CONSTRAINT chk_goals_amount_nonneg CHECK (target_amount >= 0),
  CONSTRAINT chk_goals_year_month_format CHECK (year_month ~ '^[0-9]{4}-[0-9]{2}$')
);